# HandledErrors are catch and their message printed without a stack trace
class HandledError(Exception):
    pass
